spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

logging:
  structured:
    format:
      console: logstash
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
